datasets:
  train:
    _target_: src.datasets.digicam_hf_dataset.DigiCamHFDataset
    split: train
    masks_dir: data/masks
    hf_repo: bezzam/DigiCam-Mirflickr-MultiMask-10K
    limit: null
    shuffle_index: false
    instance_transforms: null

  val:
    _target_: src.datasets.digicam_hf_dataset.DigiCamHFDataset
    split: test
    masks_dir: data/masks
    hf_repo: bezzam/DigiCam-Mirflickr-MultiMask-10K
    limit: null
    shuffle_index: false
    instance_transforms: null

writer:
  _target_: src.logger.CometMLWriter
  _recursive_: false
  project_name: pytorch_template
  workspace: null
  run_id: null
  run_name: reconstruction-speed-one-method
  mode: online
  loss_names: []
  log_checkpoints: false

device: cuda

benchmark:
  split: val
  limit: 52
  batch_size: 1
  num_workers: 0
  warmup_batches: 2
  out_dir: outputs/reconstruction_speed

method:
  name: admm100
  model_config: admm
  checkpoint_path: null

logging:
  log_comet: true
