defaults:
  - model: leadmm5_pre4_post4
  - datasets: custom_dir
  - dataloader: example
  - _self_

inferencer:
  device: auto
  seed: 1

  dataset_part: null

  from_pretrained: null
  auto_download: true
  strict_load: true

  output_dir: outputs/inference

  device_tensors:
    - measurement
    - psf
