_target_: src.logger.CometMLWriter
_recursive_: false
project_name: "pytorch_template"
workspace: null
run_name: "testing"
mode: "online"
loss_names: ["loss", "mse_loss", "lpips_loss"]
log_checkpoints: false
id_length: 32
run_id: null
